version: "3.9"

services:
  mysql:
    image: mysql:8.0.30
    stdin_open: true
    tty: true
    volumes:
      # - ./:/code
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_DATABASE: gaia_cms
      MYSQL_ROOT_PASSWORD: Minh0805!
volumes:
  data:
